config/routes.rb
Rails.application.routes.draw do
 
  devise_for :usuarios, class_name: 'Seguridad::Usuario'

  root 'home#index'

  namespace :facturacion do
    get 'pedidos/index'
    get 'pedidos_fecha/index'

    get 'cuentas_por_cliente/detalle'
    get 'cuentas_por_cliente/index'

    get 'facturacion_cuentas/detalle'
    get 'facturacion_cuentas/index'
    post 'facturacion_cuentas/facturar'

    get 'cuenta/index'
    get 'cuenta/detalle'
    post 'cuenta/imprimir_cuenta'
    post 'cuenta/cerrar_cuentas'
    post 'cuenta/abrir_cerrar_cuenta'
  end

  namespace :ventas do
    get 'venta_por_cliente/index'
    get 'venta_por_cliente/detalle'

    post 'pedidos/crear_detalle'
    patch 'pedidos/crear_detalle'
    post 'pedidos/borrar_detalle'
    post 'pedidos/rpt_lista_pedidos'
    post 'pedidos/rpt_orden_trabajo'
    post 'pedidos/rpt_etiqueta_individual'
    post 'pedidos/credito_contado'
    post 'pedidos/etiqueta'
    
    resources :pedidos
    resources :agrupador_clientes
    resources :clientes
  end

  namespace :inventario do
    resources :producto_detalles
    resources :productos
  end

end

app/models/ventas.rb
module Ventas
  def self.table_name_prefix
    'ventas.'
  end
end

app/models/ventas/agrupador_cliente.rb
class Ventas::AgrupadorCliente < ActiveRecord::Base

	strip_attributes
	has_paper_trail

	has_many :rel_cliente, class_name: 'Ventas::Cliente', foreign_key: 'id'

	scope :todos, -> { order(:nombre) }
	scope :activos, -> { where(pasivo: false).order(:nombre) }
	scope :pasivos, -> { where(pasivo: true).order(:nombre) }
end

app/models/ventas/cliente.rb
class Ventas::Cliente < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_agrupador_cliente, class_name: 'Ventas::AgrupadorCliente', foreign_key: 'agrupador_cliente_id'

	def nombre_completo
		nombre_completo = self.primer_apellido
		nombre_completo << ' '
		nombre_completo << (self.segundo_apellido.nil? ? '' : self.segundo_apellido)
		nombre_completo << ' '
		nombre_completo << self.primer_nombre
		nombre_completo << ' '
		nombre_completo << (self.segundo_nombre.nil? ? '' : self.segundo_nombre)
		nombre_completo
	end

	def primer_nombre_primer_apellido_email
		nombre_completo = self.primer_nombre
		nombre_completo << '_'
		nombre_completo << self.primer_apellido
		nombre_completo << '_'
		nombre_completo << self.email
		nombre_completo.upcase
	end

end

app/models/ventas/menu.rb
class Ventas::Menu < ActiveRecord::Base
  strip_attributes
  has_paper_trail
end

app/models/ventas/menu_detalle.rb
class Ventas::MenuDetalle < ActiveRecord::Base
  strip_attributes
  has_paper_trail
end

app/models/ventas/pedido.rb
class Ventas::Pedido < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_cliente, class_name: 'Ventas::Cliente', foreign_key: 'cliente_id'
	has_many :rel_pedido_detalle, class_name: 'Ventas::PedidoDetalle', foreign_key: 'pedido_id'
	has_one :rel_cuenta_detalle, class_name: 'Facturacion::CuentaDetalle', foreign_key:  'pedido_id'

	def al_credito?
		self.rel_cuenta_detalle.present?
	end

end

app/models/ventas/pedido_detalle.rb
class Ventas::PedidoDetalle < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_producto, class_name: 'Inventario::Producto', foreign_key: 'producto_id'
	belongs_to :rel_producto_complemento, class_name: 'Inventario::Producto', foreign_key: 'producto_complemento_id'
	belongs_to :rel_pedido, class_name: 'Ventas::Pedido', foreign_key: 'pedido_id'
end

app/controllers/facturacion/pedidos_controller.rb
class Facturacion::PedidosController < PrivateController
  def index
    @fecha = params[:fecha].blank? ? Date.today : params[:fecha]
    @agrupador = params[:agrupador]
    @monto_total = 0.0

    if @agrupador.blank?
      @ventas_pedidos = Ventas::Pedido.select('pedidos.id, clientes.email, clientes.primer_apellido, clientes.segundo_apellido, clientes.primer_nombre, clientes.segundo_nombre, agrupador_clientes.nombre as grupo').joins({:rel_cliente => :rel_agrupador_cliente}).where('pedidos.fecha = ?', @fecha)
      @monto_total = Ventas::Pedido.select('sum(pedido_detalles.cantidad*pedido_detalles.precio) as monto_total').joins(:rel_pedido_detalle).where('pedidos.fecha = ?', @fecha)[0]
    else
      @ventas_pedidos = Ventas::Pedido.select('pedidos.id, clientes.email, clientes.primer_apellido, clientes.segundo_apellido, clientes.primer_nombre, clientes.segundo_nombre, agrupador_clientes.nombre as grupo').joins({:rel_cliente => :rel_agrupador_cliente}).where('pedidos.fecha = ? and clientes.agrupador_cliente_id =?', @fecha, @agrupador)
      @monto_total = Ventas::Pedido.select('sum(pedido_detalles.cantidad*pedido_detalles.precio) as monto_total').joins(:rel_pedido_detalle,{:rel_cliente => :rel_agrupador_cliente}).where('pedidos.fecha = ? and clientes.agrupador_cliente_id =?', @fecha, @agrupador)[0]
    end

    @agrupador_cliente = Ventas::AgrupadorCliente.activos
  end

end

app/controllers/ventas/agrupador_clientes_controller.rb
class Ventas::AgrupadorClientesController < PrivateController
  before_action :set_ventas_agrupador_cliente, only: [:show, :edit, :update, :destroy]

  # GET /ventas/agrupador_clientes
  # GET /ventas/agrupador_clientes.json
  def index
    @buscar = params[:buscar].to_s
    @ventas_agrupador_clientes = Ventas::AgrupadorCliente.all.order(:nombre)
    @ventas_agrupador_clientes = @ventas_agrupador_clientes.where('nombre ilike ?', '%' + @buscar + '%') unless @buscar.blank?
  end

  # GET /ventas/agrupador_clientes/1
  # GET /ventas/agrupador_clientes/1.json
  def show
  end

  # GET /ventas/agrupador_clientes/new
  def new
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new
  end

  # GET /ventas/agrupador_clientes/1/edit
  def edit
  end

  # POST /ventas/agrupador_clientes
  # POST /ventas/agrupador_clientes.json
  def create
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new(ventas_agrupador_cliente_params)

    respond_to do |format|
      if @ventas_agrupador_cliente.save
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_agrupador_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/agrupador_clientes/1
  # PATCH/PUT /ventas/agrupador_clientes/1.json
  def update
    respond_to do |format|
      if @ventas_agrupador_cliente.update(ventas_agrupador_cliente_params)
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_agrupador_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/agrupador_clientes/1
  # DELETE /ventas/agrupador_clientes/1.json
  def destroy
    @ventas_agrupador_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_agrupador_clientes_url, notice: 'Agrupador cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventas_agrupador_cliente
      @ventas_agrupador_cliente = Ventas::AgrupadorCliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventas_agrupador_cliente_params
      params.require(:ventas_agrupador_cliente).permit(:nombre, :descripcion, :pasivo)
    end

end

app/controllers/ventas/clientes_controller.rb
class Ventas::ClientesController < PrivateController
  before_action :set_ventas_cliente, only: [:show, :edit, :update, :destroy]
  before_action :set_ventas_cliente_catalogos, only: [:new, :create, :edit, :update, :destroy]

  # GET /ventas/clientes
  # GET /ventas/clientes.json
  def index
    @agrupador = params[:agrupador]
    @buscar = params[:buscar].to_s
    @ventas_clientes = Ventas::Cliente.select('clientes.id, clientes.email, clientes.primer_apellido, clientes.segundo_apellido, clientes.primer_nombre,
                                              clientes.segundo_nombre, agrupador_clientes.nombre as grupo').joins(:rel_agrupador_cliente)
                                                                                                           .order('grupo, primer_apellido')
    @ventas_clientes = @ventas_clientes.where('clientes.agrupador_cliente_id =?', @agrupador) unless @agrupador.blank?
    @ventas_clientes = @ventas_clientes.where('concat_ws(primer_apellido, segundo_apellido, primer_nombre, segundo_nombre) ilike ?',
                                            '%' + @buscar + '%') unless @buscar.blank?
    @agrupador_cliente = Ventas::AgrupadorCliente.todos
  end

  # GET /ventas/clientes/1
  # GET /ventas/clientes/1.json
  def show
  end

  # GET /ventas/clientes/new
  def new
    @ventas_cliente = Ventas::Cliente.new
  end

  # GET /ventas/clientes/1/edit
  def edit
  end

  # POST /ventas/clientes
  # POST /ventas/clientes.json
  def create
    @ventas_cliente = Ventas::Cliente.new(ventas_cliente_params)

    respond_to do |format|
      if @ventas_cliente.save
        format.html { redirect_to @ventas_cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/clientes/1
  # PATCH/PUT /ventas/clientes/1.json
  def update
    respond_to do |format|
      if @ventas_cliente.update(ventas_cliente_params)
        format.html { redirect_to @ventas_cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/clientes/1
  # DELETE /ventas/clientes/1.json
  def destroy
    @ventas_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventas_cliente
      @ventas_cliente = Ventas::Cliente.find(params[:id])
    end

    def set_ventas_cliente_catalogos
      @agrupador = Ventas::AgrupadorCliente.activos
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventas_cliente_params
      params.require(:ventas_cliente).permit(:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :cedula, :fecha_nacimiento,
                                             :agrupador_cliente_id, :email, :piso)
    end

end

app/controllers/ventas/menu_controller.rb
class Ventas::MenuController < PrivateController

  # GET /ventas/agrupador_clientes
  # GET /ventas/agrupador_clientes.json
  def index
    @buscar = params[:buscar].to_s
    @ventas_agrupador_clientes = Ventas::AgrupadorCliente.activos
    @ventas_agrupador_clientes = @ventas_agrupador_clientes.where('nombre ilike ?', '%' + @buscar + '%') unless @buscar.blank?
  end

  # GET /ventas/agrupador_clientes/1
  # GET /ventas/agrupador_clientes/1.json
  def show
  end

  # GET /ventas/agrupador_clientes/new
  def new
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new
  end

  # GET /ventas/agrupador_clientes/1/edit
  def edit
  end

  # POST /ventas/agrupador_clientes
  # POST /ventas/agrupador_clientes.json
  def create
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new(ventas_agrupador_cliente_params)

    respond_to do |format|
      if @ventas_agrupador_cliente.save
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_agrupador_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/agrupador_clientes/1
  # PATCH/PUT /ventas/agrupador_clientes/1.json
  def update
    respond_to do |format|
      if @ventas_agrupador_cliente.update(ventas_agrupador_cliente_params)
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_agrupador_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/agrupador_clientes/1
  # DELETE /ventas/agrupador_clientes/1.json
  def destroy
    @ventas_agrupador_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_agrupador_clientes_url, notice: 'Agrupador cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/ventas/venta_por_cliente_controller.rb
class Ventas::VentaPorClienteController < PrivateController
  def index
  end

  def detalle
  end

end

app/views/ventas/pedidos/index.html.erb
<script type="text/javascript">
  function fnCreditoContado(pedidoId){
    $.post('/ventas/pedidos/credito_contado',{ id: pedidoId }, function(data){
      if (data.result) {
        if(data.contado){
          $("#btn-" + pedidoId).removeClass('btn-warning');
          $("#btn-" + pedidoId).addClass('btn-primary');
          $("#row-" + pedidoId).addClass('bg-danger');
          $("#btn-" + pedidoId).html('Pasar al Contado');
        }
        else {
          $("#btn-" + pedidoId).removeClass('btn-primary');
          $("#btn-" + pedidoId).addClass('btn-warning');
          $("#row-" + pedidoId).removeClass('bg-danger');
          $("#btn-" + pedidoId).html('Agregar a la cuenta');
        }
        new PNotify({
            title: 'Exito',
            text: data.message,
            type: 'success'
        });
      }
      else{
        new PNotify({
            title: 'Error',
            text: data.message,
            type: 'error'
        });
      }
    });
  }

  function fnEtiqueta(pedidoId){
    $.post('/ventas/pedidos/etiqueta',{ id: pedidoId }, function(data){
      if (data.result) {
        if(data.etiqueta){
          $("#etiqueta-" + pedidoId).removeClass('btn-primary');
          $("#etiqueta-" + pedidoId).addClass('btn-success');
          $("#etiqueta-" + pedidoId).html('SI');
        }
        else {
          $("#etiqueta-" + pedidoId).removeClass('btn-success');
          $("#etiqueta-" + pedidoId).addClass('btn-primary');
          $("#etiqueta-" + pedidoId).html('NO');
        }
      }
      else{
        new PNotify({
            title: 'Error',
            text: data.message,
            type: 'error'
        });
      }
    });
  }
</script>
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-12"><h3>Pedidos (<%= @ventas_pedidos.length %>)</h3></div>
        <div class="col-md-4 col-sm-4 col-xs-12"><h3>Plato Principal (<%= @cantidad_plato_principal %>)</h3></div>
        <div class="col-md-4 col-sm-4 col-xs-12"><h3>Extras (<%= @cantidad_extras %>)</h3></div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="x_panel">
      <div class="x_title">
        <div class="row">
          <div class="col-md-offset-8 col-md-2 col-sm-4 col-xs-12">
            <%= form_tag '/ventas/pedidos/rpt_orden_trabajo', {id: 'imprimir_orden', target: '_blank', method: 'post'} do %>
                <input type="hidden" name="imprimir_orden_fecha" id="imprimir_orden_fecha"/>
                <button id="imprimir_orden_btn" class="btn btn-info form-control">Orden de trabajo</button>
            <% end %>
          </div>
          <div class="col-md-2 col-sm-4 col-xs-12">
            <%= form_tag '/ventas/pedidos/rpt_lista_pedidos', {id: 'imprimir_pedidos', target: '_blank', method: 'post'} do %>
                <input type="hidden" name="imprimir_pedidos_fecha" id="imprimir_pedidos_fecha"/>
                <input type="hidden" name="imprimir_pedidos_agrupador" id="imprimir_pedidos_agrupador"/>
                <button id="imprimir_pedidos_btn" class="btn btn-info form-control">Imprimir Pedidos</button>
            <% end %>
          </div>
        </div>
        <div class="row">
          <form id="form_buscar" action="/ventas/pedidos" class="form-horizontal form-label-left">
            <div class="row">
              <label for="fecha" class="control-label col-md-1 col-sm-1 col-xs-3">
                Fecha
              </label>
              <div class="col-md-2 col-sm-3 col-xs-9">
                <input type="text" readonly="readonly" name="fecha" id="fecha" class="form-control" value="<%= @fecha %>"/>
              </div>
              <div class="col-md-3 col-sm-4 col-xs-12">
                <input placeholder="Nombre Cliente..." type="text" name="buscar" id="buscar" class="form-control" value="<%= @buscar %>"/>
              </div>
              <div class="col-md-2 col-sm-4 col-xs-12">
                <%= select_tag 'agrupador', options_for_select(@agrupador_cliente.collect { |a| [a[:nombre], a[:id]] }), {include_blank: 'Agrupador', class: 'form-control'} %>
              </div>
              <div class="col-md-2 col-sm-4 col-xs-12">
                <%= select_tag 'plato_principal', options_for_select(@nombres_platos.collect { |a| [a[:nombre], a[:id]] }), {include_blank: 'Selección', class: 'form-control'} %>
              </div>
              <div class="col-md-1 col-sm-2 col-xs-12">
                <input type="submit" value="Buscar" class="btn btn-primary form-control"/>
              </div>
              <div class="col-md-1 col-sm-2 col-xs-12">
                <%= link_to 'Nuevo', new_ventas_pedido_path, {class: 'btn btn-primary form-control'} %>
              </div>
            </div>
          </form>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content" style="display: block;">
        <div class="row bg-primary hidden-xs">
          <div class="col-md-1 col-sm-1 col-xs-1"><strong>ETIQUETA</strong></div>
          <div class="col-md-1 col-sm-1 col-xs-1"><strong>HORA</strong></div>
          <div class="col-md-7 col-sm-7 col-xs-7"><strong>PEDIDO</strong></div>
          <div class="col-md-1 col-sm-1 col-xs-1"><strong>TOTAL</strong></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><strong>ACCIONES</strong></div>
        </div>
        <br>
        <% @ventas_pedidos.each do |ventas_pedido| %>
            <div id="row-<%= ventas_pedido.id %>" class="row <%= ventas_pedido.al_credito? ? 'bg-danger' : '' %> ">
              <div class="col-md-1 col-sm-1 col-xs-12">
                <% if ventas_pedido.etiqueta %>
                  <button id="etiqueta-<%= ventas_pedido.id %>" class="btn btn-xs btn-success" onclick="fnEtiqueta(<%= ventas_pedido.id %>)">SI</button>
                <% else %>
                   <button  id="etiqueta-<%= ventas_pedido.id %>" class="btn btn-xs btn-primary" onclick="fnEtiqueta(<%= ventas_pedido.id %>)">NO</button>
                <% end %>
              </div>
              <div class="col-md-1 col-sm-1 col-xs-12">
                <%= ventas_pedido.created_at.strftime('%H:%M:%S') %>
              </div>
              <div class="col-md-7 col-sm-7 col-xs-12">
                <div class="row">
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <a href="/ventas/pedidos/<%= ventas_pedido.id %>">
                      <b>
                        <%= ventas_pedido.grupo %> /
                        <%= ventas_pedido.email %> /
                        <%= ventas_pedido.primer_apellido %>
                        <%= ventas_pedido.segundo_apellido %>
                        <%= ventas_pedido.primer_nombre %>
                        <%= ventas_pedido.segundo_nombre %> /
                        <%= ventas_pedido.piso %>
                      </b>
                    </a>
                  </div>
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <% ventas_pedido.rel_pedido_detalle.each do |pd| %>
                        <div class="row <%= pd.observacion.nil? ? '' : 'bg-info' %>">
                          <div class="col-md-7 col-sm-7 col-xs-7  ">
                            <%= pd.rel_producto.nombre %>
                            <% unless pd.rel_producto_complemento.nil? %>
                                &nbsp;CON&nbsp; <%= pd.rel_producto_complemento.nombre %>
                            <% end %>
                            <% unless pd.observacion.nil? %>
                                <br>&nbsp;(&nbsp;<%= pd.observacion %>&nbsp;)&nbsp;
                            <% end %>
                          </div>
                          <div class="col-md-1 col-sm-1 col-xs-2"><%= pd.precio %></div>
                          <div class="col-md-1 col-sm-1 col-xs-1"><%= pd.cantidad %></div>
                          <div class="col-md-1 col-sm-1 col-xs-2"><%= pd.precio * pd.cantidad %></div>
                        </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col-md-1 col-sm-1 col-xs-12">
                <strong>
                  <%=
                    total = 0.0
                    ventas_pedido.rel_pedido_detalle.each { |pd| total = total + pd.cantidad * pd.precio }
                    total
                  %>
                </strong>
              </div>
              <div class="col-md-2 col-sm-3 col-xs-12">
                <% if ventas_pedido.al_credito? %>
                  <button id="btn-<%= ventas_pedido.id %>" class="btn btn-primary form-control" onclick="fnCreditoContado(<%= ventas_pedido.id %>)">Pasar al Contado</button>
                <% else %>
                   <button  id="btn-<%= ventas_pedido.id %>" class="btn btn-warning form-control" onclick="fnCreditoContado(<%= ventas_pedido.id %>)">Agregar a la cuenta</button>
                <% end %>
              </div>
            </div>
            <br>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {

    $('#fecha').daterangepicker({
      singleDatePicker: true,
      calender_style: "picker_4",
      format: 'YYYY-MM-DD',
      showDropdowns: true
    });

    function fn_imprimir_orden_trabajo() {
      $('#imprimir_orden_fecha').val($('#fecha').val());
      $('#imprimir_orden').submit();
    }

    function fn_imprimir_lista_pedidos() {
      var agrupador = $('#agrupador').val();
      if (agrupador == "") {
        new PNotify({
              title: 'Error',
              text: 'Seleccione el Agrupador',
              type: 'error'
          });
        return false;
      }

      $('#imprimir_pedidos_fecha').val($('#fecha').val());
      $('#imprimir_pedidos_agrupador').val(agrupador);
      $('#imprimir_pedidos').submit();
    }

    $('#agrupador').val('<%=@agrupador%>');
    $('#plato_principal').val('<%=@plato_principal%>');
    $('#imprimir_pedidos_btn').click(fn_imprimir_lista_pedidos);
    $('#imprimir_orden_btn').click(fn_imprimir_orden_trabajo);

  });
</script>

app/views/ventas/pedidos/new.html.erb
<%= form_for @ventas_pedido, html: {class: 'form-horizontal form-label-left'} do |f| %>

    <% if @ventas_pedido.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ventas_pedido.errors.count, "error") %> prohibited this ventas_pedido from being saved:</h2>

          <ul>
            <% @ventas_pedido.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nuevo Pedido</h3>
      </div>
      <div class="title_right">
        <div class="form-group pull-right">
          <%= f.submit 'Guadar', {class: 'btn btn btn-success'} %>
          <%= link_to 'Cancelar', ventas_pedidos_path, {class: 'btn btn-primary'} %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">

            <div class="form-group">
              <label for="ventas_cliente_agrupador_cliente_id" class="control-label col-md-3 col-sm-3 col-xs-12">
                Fecha
                <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :fecha, {value: Date.today, readonly:'readonly', class: 'form-control col-md-7 col-xs-12', required: 'required'} %>
              </div>
            </div>

            <div class="form-group">
              <label for="ventas_cliente_agrupador_cliente_id" class="control-label col-md-3 col-sm-3 col-xs-12">
                Cliente
                <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.collection_select(:cliente_id, @clientes, :id, :nombre, {include_blank: true}, {class: 'form-control col-md-7 col-xs-12', required: 'required'}) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
    <script>
      $(document).ready(function() {

        $("#ventas_pedido_cliente_id").select2({
          placeholder: "Seleccione un cliente",
          allowClear: true
        });

        $('#ventas_pedido_fecha').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
          format: 'YYYY-MM-DD',
          showDropdowns: true,
          maxDate: '<%= Date.today %>'
        });

      });
    </script>
<% end %>