config/routes.rb
Rails.application.routes.draw do
 
  devise_for :usuarios, class_name: 'Seguridad::Usuario'

  root 'home#index'

  namespace :facturacion do
    get 'pedidos/index'
    get 'pedidos_fecha/index'

    get 'cuentas_por_cliente/detalle'
    get 'cuentas_por_cliente/index'

    get 'facturacion_cuentas/detalle'
    get 'facturacion_cuentas/index'
    post 'facturacion_cuentas/facturar'

    get 'cuenta/index'
    get 'cuenta/detalle'
    post 'cuenta/imprimir_cuenta'
    post 'cuenta/cerrar_cuentas'
    post 'cuenta/abrir_cerrar_cuenta'
  end

  namespace :ventas do
    get 'venta_por_cliente/index'
    get 'venta_por_cliente/detalle'

    post 'pedidos/crear_detalle'
    patch 'pedidos/crear_detalle'
    post 'pedidos/borrar_detalle'
    post 'pedidos/rpt_lista_pedidos'
    post 'pedidos/rpt_orden_trabajo'
    post 'pedidos/rpt_etiqueta_individual'
    post 'pedidos/credito_contado'
    post 'pedidos/etiqueta'
    
    resources :pedidos
    resources :agrupador_clientes
    resources :clientes
  end

  namespace :inventario do
    resources :producto_detalles
    resources :productos
  end

end

app/models/inventario.rb
module Inventario
  def self.table_name_prefix
    'inventario.'
  end
end

app/models/inventario/categoria_producto.rb
class Inventario::CategoriaProducto < ActiveRecord::Base
  strip_attributes
  has_paper_trail

  has_many :rel_producto, class_name: 'Inventario::Producto', foreign_key: 'categoria_producto_id'
end

app/models/inventario/producto.rb
class Inventario::Producto < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	has_many :rel_pedido_detalle, class_name: 'Ventas::PedidoDetalle', foreign_key: 'producto_id'
  belongs_to :rel_categoria_producto, class_name: 'Inventario::CategoriaProducto', foreign_key: 'categoria_producto_id'
end

app/models/inventario/producto_detalle.rb
class Inventario::ProductoDetalle < ActiveRecord::Base
  strip_attributes
  has_paper_trail
end

app/controllers/inventario/producto_detalles_controller.rb
class Inventario::ProductoDetallesController < PrivateController
  before_action :set_inventario_producto_detalle, only: [:show, :edit, :update, :destroy]

  # GET /inventario/producto_detalles
  # GET /inventario/producto_detalles.json
  def index
    @inventario_producto_detalles = Inventario::ProductoDetalle.all
  end

  # GET /inventario/producto_detalles/1
  # GET /inventario/producto_detalles/1.json
  def show
  end

  # GET /inventario/producto_detalles/new
  def new
    @inventario_producto_detalle = Inventario::ProductoDetalle.new
  end

  # GET /inventario/producto_detalles/1/edit
  def edit
  end

  # POST /inventario/producto_detalles
  # POST /inventario/producto_detalles.json
  def create
    @inventario_producto_detalle = Inventario::ProductoDetalle.new(inventario_producto_detalle_params)

    respond_to do |format|
      if @inventario_producto_detalle.save
        format.html { redirect_to @inventario_producto_detalle, notice: 'Producto detalle was successfully created.' }
        format.json { render :show, status: :created, location: @inventario_producto_detalle }
      else
        format.html { render :new }
        format.json { render json: @inventario_producto_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventario/producto_detalles/1
  # PATCH/PUT /inventario/producto_detalles/1.json
  def update
    respond_to do |format|
      if @inventario_producto_detalle.update(inventario_producto_detalle_params)
        format.html { redirect_to @inventario_producto_detalle, notice: 'Producto detalle was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventario_producto_detalle }
      else
        format.html { render :edit }
        format.json { render json: @inventario_producto_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventario/producto_detalles/1
  # DELETE /inventario/producto_detalles/1.json
  def destroy
    @inventario_producto_detalle.destroy
    respond_to do |format|
      format.html { redirect_to inventario_producto_detalles_url, notice: 'Producto detalle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario_producto_detalle
      @inventario_producto_detalle = Inventario::ProductoDetalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventario_producto_detalle_params
      params.require(:inventario_producto_detalle).permit(:producto_id, :nombre, :descripcion)
    end

end

app/controllers/inventario/productos_controller.rb
class Inventario::ProductosController < PrivateController
  before_action :set_inventario_producto, only: [:show, :edit, :update, :destroy]
  before_action :set_catalogos, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /inventario/productos
  # GET /inventario/productos.json
  def index
    @categoria_id = params[:categoria]
    @buscar = params[:buscar].to_s
    @inventario_productos  = Inventario::Producto.select('productos.id, productos.nombre, productos.precio, categoria_productos.nombre as categoria')
                                                 .joins(:rel_categoria_producto).order('productos.nombre')
    @inventario_productos = @inventario_productos.where('productos.nombre ilike ?',  '%' + @buscar + '%') unless @buscar.blank?
    @inventario_productos = @inventario_productos.where(categoria_producto_id: @categoria_id) unless @categoria_id.blank?
  end

  # GET /inventario/productos/1
  # GET /inventario/productos/1.json
  def show
  end

  # GET /inventario/productos/new
  def new
    @inventario_producto = Inventario::Producto.new
  end

  # GET /inventario/productos/1/edit
  def edit
  end

  # POST /inventario/productos
  # POST /inventario/productos.json
  def create
    @inventario_producto = Inventario::Producto.new(inventario_producto_params)

    respond_to do |format|
      if @inventario_producto.save
        format.html { redirect_to @inventario_producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @inventario_producto }
      else
        format.html { render :new }
        format.json { render json: @inventario_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventario/productos/1
  # PATCH/PUT /inventario/productos/1.json
  def update
    respond_to do |format|
      if @inventario_producto.update(inventario_producto_params)
        format.html { redirect_to @inventario_producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventario_producto }
      else
        format.html { render :edit }
        format.json { render json: @inventario_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventario/productos/1
  # DELETE /inventario/productos/1.json
  def destroy
    @inventario_producto.destroy
    respond_to do |format|
      format.html { redirect_to inventario_productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario_producto
      @inventario_producto = Inventario::Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventario_producto_params
      params.require(:inventario_producto).permit(:nombre, :descripcion, :precio, :interno, :categoria_producto_id, :pasivo)
    end

    def set_catalogos
      @categorias = Inventario::CategoriaProducto.select('*').where(pasivo: false).order('nombre')
    end

end

app/views/inventario/productos/_form.html.erb
<% if @inventario_producto.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@inventario_producto.errors.count, "error") %> prohibited this inventario_producto from being saved:</h2>
  <ul>
    <% @inventario_producto.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <label for="inventario_producto_primer_nombre" class="control-label col-md-3 col-sm-3 col-xs-12">
    Agrupador
    <span class="required">*</span>
  </label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.collection_select(:categoria_producto_id, @categorias, :id, :nombre, {include_blank: true}, {class: 'form-control col-md-7 col-xs-12',
                                                                                                   required: 'required'}) %>
  </div>
</div>

<div class="form-group">
  <label for="inventario_producto_nombre" class="control-label col-md-3 col-sm-3 col-xs-12">
    Nombre
    <span class="required">*</span>
  </label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :nombre, {class: 'form-control col-md-7 col-xs-12', required: 'required'} %>
  </div>
</div>
<div class="form-group">
<%= f.label :descripcion, 'Descripción', {class: 'control-label col-md-3 col-sm-3 col-xs-12'} %>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_area :descripcion, {class: 'form-control col-md-7 col-xs-12'} %>
  </div>
</div>
<div class="form-group">
  <label for="inventario_producto_precio" class="control-label col-md-3 col-sm-3 col-xs-12">
    Precio
    <span class="required">*</span>
  </label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :precio, {class: 'form-control col-md-7 col-xs-12 has-feedback-left', required: 'required'} %>
    <span aria-hidden="true" class="fa fa-money form-control-feedback left"></span>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-3 col-md-6 col-sm-6 col-xs-12">
    <div class="checkbox">
      <label>
      <%= f.check_box :interno %>
        Interno
      </label>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-3 col-md-6 col-sm-6 col-xs-12">
    <div class="checkbox">
      <label>
        <%= f.check_box :pasivo %>
        Pasivo
      </label>
    </div>
  </div>
</div>
<div class="ln_solid"></div>

app/views/inventario/productos/edit.html.erb
<!-- page content -->
<%= form_for @inventario_producto, html: {class: 'form-horizontal form-label-left'} do |f| %>
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
				<h3>Editar Producto ID: <%= @inventario_producto.id %></h3>
			</div>  
			<div class="title_right">
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<div class="form-group pull-right">
							<%= f.submit 'Guadar', {class: 'btn btn btn-success'} %>
							<%= link_to 'Cancelar', inventario_productos_path, {class: 'btn btn-primary'} %>
						</div>    
						<div class="clearfix"></div>
					</div>
					<div class="x_content" style="display: block;">
						<%= render :partial => "form", :locals => {:f => f} %> 
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>
<!-- /page content -->

app/views/inventario/productos/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Productos</h3>
      </div> 
      <div class="title_right">
      </div>          
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="row">
              <form id="form_buscar" action="/inventario/productos" class="form-horizontal form-label-left">
                <div class="col-md-3 col-sm-3 col-xs-3">
                  <input placeholder="Buscar..." type="text" name="buscar" id="buscar" class="form-control col-md-7 col-xs-12" value="<%=@buscar%>"/>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3">
                  <%= select_tag 'categoria', options_for_select(@categorias.collect {|a| [ a[:nombre], a[:id] ] }),{ include_blank: true, class:
                      'form-control' } %>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3">
                  <input type="submit" value="Buscar" class="btn btn-primary"/>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3">
                  <div class="pull-right">
                    <%= link_to 'Nuevo', new_inventario_producto_path, {class: 'btn btn-success'} %>
                  </div>
                </div>
              </form>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">
              <ul class="content-list">
                <% @inventario_productos.each do |inventario_producto| %>
                    <li>
                      <h5>
                      <div class="row">
                        <div class="col-md-10 col-sm-10 col-xs-10">
                            <small><%= inventario_producto.categoria %></small> /
                            <a href="/inventario/productos/<%= inventario_producto.id %>">
                              <%= inventario_producto.nombre %>
                            </a>
                        </div>
                        <div class="col-md-2 col-sm-2 col-xs-2">
                          <div class="pull-right">
                            <%= inventario_producto.precio %>
                          </div>
                        </div>
                      </div>
                      </h5>
                    </li>
                  <% end %>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->
<script>
  $(document).ready(function() {
    $('#categoria').val('<%=@categoria_id%>');
  });
</script>

app/views/inventario/productos/new.html.erb
<!-- page content -->
<%= form_for @inventario_producto, html: {class: 'form-horizontal form-label-left'} do |f| %>
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nuevo Producto</h3>
      </div>  
      <div class="title_right">
        <div class="form-group pull-right">
          <%= f.submit 'Guadar', {class: 'btn btn btn-success'} %>
          <%= link_to 'Cancelar', inventario_productos_path, {class: 'btn btn-primary'} %>
        </div>     
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">
           <%= render :partial => "form", :locals => {:f => f} %> 
         </div>
       </div>
     </div>
   </div>
 </div>
</div>
<% end %>
<!-- /page content -->

app/views/inventario/productos/show.html.erb
<div class="form-horizontal form-label-left">
	<div class="right_col" role="main">
		<div class="page-title">
			<div class="title_left">
				<h3>Producto ID: <%= @inventario_producto.id %></h3>
			</div>  
			<div class="title_right">
			</div>     
		</div>
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<div class="form-group pull-right">
							<%= link_to 'Editar', edit_inventario_producto_path(@inventario_producto), {class: 'btn btn-success'} %>
							<%= link_to 'Eliminar', @inventario_producto, :class => 'btn btn-danger', :method => :delete, :data => { :confirm => 'Estás Seguro?' } %>
							<%= link_to 'Regresar', inventario_productos_path, {class: 'btn btn-primary'} %>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="x_content" style="display: block;">
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                Categoría
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= @inventario_producto.rel_categoria_producto.nombre %>
              </div>
            </div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">
								Nombre
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<%= @inventario_producto.nombre %>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">
								Descripción
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<%= @inventario_producto.descripcion %>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12">
								Precio
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<%= @inventario_producto.precio %>
							</div>
						</div> 
						<div class="ln_solid"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>