config/routes.rb
Rails.application.routes.draw do
 
  devise_for :usuarios, class_name: 'Seguridad::Usuario'

  root 'home#index'

  namespace :facturacion do
    get 'pedidos/index'
    get 'pedidos_fecha/index'

    get 'cuentas_por_cliente/detalle'
    get 'cuentas_por_cliente/index'

    get 'facturacion_cuentas/detalle'
    get 'facturacion_cuentas/index'
    post 'facturacion_cuentas/facturar'

    get 'cuenta/index'
    get 'cuenta/detalle'
    post 'cuenta/imprimir_cuenta'
    post 'cuenta/cerrar_cuentas'
    post 'cuenta/abrir_cerrar_cuenta'
  end

  namespace :ventas do
    get 'venta_por_cliente/index'
    get 'venta_por_cliente/detalle'

    post 'pedidos/crear_detalle'
    patch 'pedidos/crear_detalle'
    post 'pedidos/borrar_detalle'
    post 'pedidos/rpt_lista_pedidos'
    post 'pedidos/rpt_orden_trabajo'
    post 'pedidos/rpt_etiqueta_individual'
    post 'pedidos/credito_contado'
    post 'pedidos/etiqueta'
    
    resources :pedidos
    resources :agrupador_clientes
    resources :clientes
  end

  namespace :inventario do
    resources :producto_detalles
    resources :productos
  end

end

app/models/ventas.rb
module Ventas
  def self.table_name_prefix
    'ventas.'
  end
end

app/models/ventas/agrupador_cliente.rb
class Ventas::AgrupadorCliente < ActiveRecord::Base

	strip_attributes
	has_paper_trail

	has_many :rel_cliente, class_name: 'Ventas::Cliente', foreign_key: 'id'

	scope :todos, -> { order(:nombre) }
	scope :activos, -> { where(pasivo: false).order(:nombre) }
	scope :pasivos, -> { where(pasivo: true).order(:nombre) }
end

app/models/ventas/cliente.rb
class Ventas::Cliente < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_agrupador_cliente, class_name: 'Ventas::AgrupadorCliente', foreign_key: 'agrupador_cliente_id'

	def nombre_completo
		nombre_completo = self.primer_apellido
		nombre_completo << ' '
		nombre_completo << (self.segundo_apellido.nil? ? '' : self.segundo_apellido)
		nombre_completo << ' '
		nombre_completo << self.primer_nombre
		nombre_completo << ' '
		nombre_completo << (self.segundo_nombre.nil? ? '' : self.segundo_nombre)
		nombre_completo
	end

	def primer_nombre_primer_apellido_email
		nombre_completo = self.primer_nombre
		nombre_completo << '_'
		nombre_completo << self.primer_apellido
		nombre_completo << '_'
		nombre_completo << self.email
		nombre_completo.upcase
	end

end

app/models/ventas/menu.rb
class Ventas::Menu < ActiveRecord::Base
  strip_attributes
  has_paper_trail
end

app/models/ventas/menu_detalle.rb
class Ventas::MenuDetalle < ActiveRecord::Base
  strip_attributes
  has_paper_trail
end

app/models/ventas/pedido.rb
class Ventas::Pedido < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_cliente, class_name: 'Ventas::Cliente', foreign_key: 'cliente_id'
	has_many :rel_pedido_detalle, class_name: 'Ventas::PedidoDetalle', foreign_key: 'pedido_id'
	has_one :rel_cuenta_detalle, class_name: 'Facturacion::CuentaDetalle', foreign_key:  'pedido_id'

	def al_credito?
		self.rel_cuenta_detalle.present?
	end

end

app/models/ventas/pedido_detalle.rb
class Ventas::PedidoDetalle < ActiveRecord::Base
	strip_attributes
	has_paper_trail

	belongs_to :rel_producto, class_name: 'Inventario::Producto', foreign_key: 'producto_id'
	belongs_to :rel_producto_complemento, class_name: 'Inventario::Producto', foreign_key: 'producto_complemento_id'
	belongs_to :rel_pedido, class_name: 'Ventas::Pedido', foreign_key: 'pedido_id'
end

app/controllers/ventas/agrupador_clientes_controller.rb
class Ventas::AgrupadorClientesController < PrivateController
  before_action :set_ventas_agrupador_cliente, only: [:show, :edit, :update, :destroy]

  # GET /ventas/agrupador_clientes
  # GET /ventas/agrupador_clientes.json
  def index
    @buscar = params[:buscar].to_s
    @ventas_agrupador_clientes = Ventas::AgrupadorCliente.all.order(:nombre)
    @ventas_agrupador_clientes = @ventas_agrupador_clientes.where('nombre ilike ?', '%' + @buscar + '%') unless @buscar.blank?
  end

  # GET /ventas/agrupador_clientes/1
  # GET /ventas/agrupador_clientes/1.json
  def show
  end

  # GET /ventas/agrupador_clientes/new
  def new
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new
  end

  # GET /ventas/agrupador_clientes/1/edit
  def edit
  end

  # POST /ventas/agrupador_clientes
  # POST /ventas/agrupador_clientes.json
  def create
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new(ventas_agrupador_cliente_params)

    respond_to do |format|
      if @ventas_agrupador_cliente.save
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_agrupador_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/agrupador_clientes/1
  # PATCH/PUT /ventas/agrupador_clientes/1.json
  def update
    respond_to do |format|
      if @ventas_agrupador_cliente.update(ventas_agrupador_cliente_params)
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_agrupador_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/agrupador_clientes/1
  # DELETE /ventas/agrupador_clientes/1.json
  def destroy
    @ventas_agrupador_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_agrupador_clientes_url, notice: 'Agrupador cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventas_agrupador_cliente
      @ventas_agrupador_cliente = Ventas::AgrupadorCliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventas_agrupador_cliente_params
      params.require(:ventas_agrupador_cliente).permit(:nombre, :descripcion, :pasivo)
    end

end

app/controllers/ventas/clientes_controller.rb
class Ventas::ClientesController < PrivateController
  before_action :set_ventas_cliente, only: [:show, :edit, :update, :destroy]
  before_action :set_ventas_cliente_catalogos, only: [:new, :create, :edit, :update, :destroy]

  # GET /ventas/clientes
  # GET /ventas/clientes.json
  def index
    @agrupador = params[:agrupador]
    @buscar = params[:buscar].to_s
    @ventas_clientes = Ventas::Cliente.select('clientes.id, clientes.email, clientes.primer_apellido, clientes.segundo_apellido, clientes.primer_nombre,
                                              clientes.segundo_nombre, agrupador_clientes.nombre as grupo').joins(:rel_agrupador_cliente)
                                                                                                           .order('grupo, primer_apellido')
    @ventas_clientes = @ventas_clientes.where('clientes.agrupador_cliente_id =?', @agrupador) unless @agrupador.blank?
    @ventas_clientes = @ventas_clientes.where('concat_ws(primer_apellido, segundo_apellido, primer_nombre, segundo_nombre) ilike ?',
                                            '%' + @buscar + '%') unless @buscar.blank?
    @agrupador_cliente = Ventas::AgrupadorCliente.todos
  end

  # GET /ventas/clientes/1
  # GET /ventas/clientes/1.json
  def show
  end

  # GET /ventas/clientes/new
  def new
    @ventas_cliente = Ventas::Cliente.new
  end

  # GET /ventas/clientes/1/edit
  def edit
  end

  # POST /ventas/clientes
  # POST /ventas/clientes.json
  def create
    @ventas_cliente = Ventas::Cliente.new(ventas_cliente_params)

    respond_to do |format|
      if @ventas_cliente.save
        format.html { redirect_to @ventas_cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/clientes/1
  # PATCH/PUT /ventas/clientes/1.json
  def update
    respond_to do |format|
      if @ventas_cliente.update(ventas_cliente_params)
        format.html { redirect_to @ventas_cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/clientes/1
  # DELETE /ventas/clientes/1.json
  def destroy
    @ventas_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventas_cliente
      @ventas_cliente = Ventas::Cliente.find(params[:id])
    end

    def set_ventas_cliente_catalogos
      @agrupador = Ventas::AgrupadorCliente.activos
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventas_cliente_params
      params.require(:ventas_cliente).permit(:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :cedula, :fecha_nacimiento,
                                             :agrupador_cliente_id, :email, :piso)
    end

end

app/controllers/ventas/menu_controller.rb
class Ventas::MenuController < PrivateController

  # GET /ventas/agrupador_clientes
  # GET /ventas/agrupador_clientes.json
  def index
    @buscar = params[:buscar].to_s
    @ventas_agrupador_clientes = Ventas::AgrupadorCliente.activos
    @ventas_agrupador_clientes = @ventas_agrupador_clientes.where('nombre ilike ?', '%' + @buscar + '%') unless @buscar.blank?
  end

  # GET /ventas/agrupador_clientes/1
  # GET /ventas/agrupador_clientes/1.json
  def show
  end

  # GET /ventas/agrupador_clientes/new
  def new
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new
  end

  # GET /ventas/agrupador_clientes/1/edit
  def edit
  end

  # POST /ventas/agrupador_clientes
  # POST /ventas/agrupador_clientes.json
  def create
    @ventas_agrupador_cliente = Ventas::AgrupadorCliente.new(ventas_agrupador_cliente_params)

    respond_to do |format|
      if @ventas_agrupador_cliente.save
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully created.' }
        format.json { render :show, status: :created, location: @ventas_agrupador_cliente }
      else
        format.html { render :new }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventas/agrupador_clientes/1
  # PATCH/PUT /ventas/agrupador_clientes/1.json
  def update
    respond_to do |format|
      if @ventas_agrupador_cliente.update(ventas_agrupador_cliente_params)
        format.html { redirect_to @ventas_agrupador_cliente, notice: 'Agrupador cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventas_agrupador_cliente }
      else
        format.html { render :edit }
        format.json { render json: @ventas_agrupador_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventas/agrupador_clientes/1
  # DELETE /ventas/agrupador_clientes/1.json
  def destroy
    @ventas_agrupador_cliente.destroy
    respond_to do |format|
      format.html { redirect_to ventas_agrupador_clientes_url, notice: 'Agrupador cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/ventas/venta_por_cliente_controller.rb
class Ventas::VentaPorClienteController < PrivateController
  def index
  end

  def detalle
  end

end

app/views/ventas/menu/_form.html.erb
<%= form_for(@ventas_agrupador_cliente) do |f| %>
  <% if @ventas_agrupador_cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ventas_agrupador_cliente.errors.count, "error") %> prohibited this ventas_agrupador_cliente from being saved:</h2>
      <ul>
      <% @ventas_agrupador_cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="form-group">
  <label for="inventario_producto_primer_nombre" class="control-label col-md-3 col-sm-3 col-xs-12">
    Nombre
    <span class="required">*</span>
  </label>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_field :nombre, {class: 'form-control col-md-7 col-xs-12', required: 'required'} %>
  </div>
</div>
<div class="form-group">
  <%= f.label :descripcion, 'Descripción', {class: 'control-label col-md-3 col-sm-3 col-xs-12'} %>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <%= f.text_area :descripcion, {class: 'form-control col-md-7 col-xs-12'} %>
  </div>
</div>

app/views/ventas/menu/edit.html.erb
<%= form_for @ventas_agrupador_cliente, html: {class: 'form-horizontal form-label-left'} do |f| %>
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Editar Agrupador ID: <%= @ventas_agrupador_cliente.id %></h3>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="x_panel">
          <div class="x_title">
            <div class="form-group pull-right">
              <%= f.submit 'Guadar', {class: 'btn btn btn-success'} %>
              <%= link_to 'Cancelar', ventas_agrupador_clientes_path, {class: 'btn btn-primary'} %>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">
            <%= render :partial => 'form', :locals => {:f => f} %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/ventas/menu/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Agrupador clientes</h3>
      </div>
    </div>
    <div class="clearfix"></div>
        <div class="x_panel">
          <div class="x_title">
            <div class="row">
              <form id="form_buscar" action="/ventas/agrupador_clientes" class="form-horizontal form-label-left">
                <div class="row">
                  <div class="col-md-3 col-sm-6 col-xs-12">
                    <input placeholder="Nombre ..." type="text" name="buscar" id="buscar" class="form-control" value="<%= @buscar %>"/>
                  </div>
                  <div class="col-md-2 col-sm-3 col-xs-12">
                    <input type="submit" value="Buscar" class="btn btn-primary form-control"/>
                  </div>
                  <div class="col-md-offset-5 col-md-2 col-sm-3 col-xs-12">
                    <%= link_to 'Nuevo', new_ventas_agrupador_cliente_path, {class: 'btn btn-primary form-control'} %>
                  </div>
                </div>
              </form>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">
            <div class="row bg-primary hidden-xs">
              <div class="col-md-10 col-sm-10 col-xs-10"><strong>AGRUPADOR</strong></div>
              <div class="col-md-2 col-sm-2 col-xs-2"><strong>ACCIONES</strong></div>
            </div>
            <br>
            <% @ventas_agrupador_clientes.each do |r| %>
                <div class="row">
                  <div class="col-md-11 col-sm-10 col-xs-12">
                    <a href="/ventas/agrupador_clientes/<%= r.id %>">
                      <b>
                        <%= r.nombre %> <br>
                      </b>
                      <%= r.descripcion %>
                    </a>
                  </div>
                  <div class="col-md-1 col-sm-2 col-xs-12">
                    <a class="btn btn-primary form-control" href="/ventas/agrupador_clientes/<%= r.id %>">Editar</a>
                  </div>
                </div>
                <br>
            <% end %>
          </div>
        </div>
      </div>
</div>
<!-- /page content -->

app/views/ventas/menu/new.html.erb
<%= form_for @ventas_agrupador_cliente, html: {class: 'form-horizontal form-label-left'} do |f| %>
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Nuevo Producto</h3>
          </div>
          <div class="title_right">
            <div class="form-group pull-right">
              <%= f.submit 'Guadar', {class: 'btn btn btn-success'} %>
              <%= link_to 'Cancelar', ventas_agrupador_clientes_path, {class: 'btn btn-primary'} %>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="x_panel">
          <div class="x_title">
            <div class="clearfix"></div>
          </div>
          <div class="x_content" style="display: block;">
            <%= render :partial => 'form', :locals => {:f => f} %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/ventas/menu/show.html.erb
<div class="form-horizontal form-label-left">
  <div class="right_col" role="main">
    <div class="page-title">
      <div class="title_left">
        <h3>Agrupador ID: <%= @ventas_agrupador_cliente.id %></h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="x_panel">
      <div class="x_title">
        <div class="form-group pull-right">
          <%= link_to 'Editar', edit_ventas_agrupador_cliente_path(@ventas_agrupador_cliente), {class: 'btn btn-success'} %>
          <%= link_to 'Eliminar', @ventas_agrupador_cliente, :class => 'btn btn-danger', :method => :delete, :data => {:confirm => 'Estás Seguro?'} %>
          <%= link_to 'Regresar', ventas_agrupador_clientes_path, {class: 'btn btn-primary'} %>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content" style="display: block;">
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Nombre
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= @ventas_agrupador_cliente.nombre %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Descripción
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= @ventas_agrupador_cliente.descripcion %>
          </div>
        </div>
        <div class="ln_solid"></div>
      </div>
    </div>
  </div>
</div>